# Generated by Django 3.0 on 2022-12-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221221_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_description',
            name='Skill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Skill'),
        ),
        migrations.AddField(
            model_name='job_description',
            name='qualifications_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Qualifications'),
        ),
        migrations.AddField(
            model_name='job_description',
            name='responsibilites_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Responsibilites'),
        ),
    ]
