# Generated by Django 3.0 on 2022-12-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20221226_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_description',
            name='Skill_id',
        ),
        migrations.RemoveField(
            model_name='job_description',
            name='qualifications_id',
        ),
        migrations.RemoveField(
            model_name='job_description',
            name='responsibilites_id',
        ),
    ]
